### PR TITLE
feat(setup): Setup up the project.

### PR DESCRIPTION
**Pull request by anishshobithps**
Additions:
 - Eslint
 - Prettier
 - CI
 - Workflows

### CODE REVIEW

**Comment by anishshobithps** [comment]
cc @acollierr17 @Strandxo @JonasSchiott

**Review by t3ned — APPROVED** [review]
Looks good to me. You may want to add the commit scheme you're following to the README or a CONTRIBUTING file.

**Comment by t3ned** [comment]
Perfect looks great! :)

**Comment by Strandxo** [comment]
Looks good to me

**Comment by anishshobithps** [comment]
Before merging i would still wait for others approval!

**Review by JonasSchiott — APPROVED** [review]
Seems perfect, feel free to merge!

**Pull request merged**
